### ISSUE TITLE
Build the Supplier READ Service

### ISSUE THREAD

**Issue by joyceluyy** [nyusuppliers/suppliers#5]
**As a** shopping website manager
**I need** the functionality to get detailed information of certain suppliers
**So that** we can understand the type and quantity of product offered by the suppliers and other relevant attributes such as name, id, rating etc. 

**Assumptions:** 

* The READ service will be part of the routes.py file
* The test cases will be part of the test_routes.py file

**Acceptance Criteria:**

```
When API call on route "GET /suppliers/id"
Then the service should return the suppliers of interests with their corresponding detailed information with return code 200.
```

**Comment by gdrdrdr** [comment]
**As a** User
**I need** the ability to update entry in supplier
**So that** I can change existing entry

**Assumptions:**

- The UPDATE service will be part of the supplier_service.py file
- The test cases for UPDATE service will be part of the test_supplier_service.py file

**Acceptance Criteria:**

```
When I call ‘UPDATE /supplier/0001/id/0002’
It updates the supplier with id 0001. Change its id to 0002
When I call ‘UPDATE /supplier/0001/name/a_company’
It updates the supplier with id 0001. Change its name to a_company

```
